const express = require('express');
const PDFDocument = require('pdfkit');
const reportStore = require('../reportStore');

const router = express.Router();

function fmt(n) {
  if (n === null || n === undefined || isNaN(n)) return '—';
  return Number(n).toLocaleString('en-IN', { maximumFractionDigits: 1 });
}

// GET /api/export-pdf?reportId=...
router.get('/', async (req, res) => {
  const { reportId } = req.query;
  const report = reportId && reportStore.get(reportId);
  if (!report) {
    return res.status(404).json({ error: 'Report not found — it may have expired. Please re-analyze the document.' });
  }
  const a = report.analysis;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${(a.company_name || 'report').replace(/[^a-z0-9]+/gi, '_')}_ledger_report.pdf"`
  );

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.font('Helvetica-Bold').fontSize(20).text(a.company_name || 'Company Report');
  doc.font('Helvetica').fontSize(10).fillColor('#555').text(`${a.sector || ''}   •   Generated by Ledger — Annual Report Analyst`);
  doc.moveDown(1.2);

  doc.fillColor('#000').font('Helvetica-Bold').fontSize(13).text('Business Summary');
  doc.font('Helvetica').fontSize(10.5).text(report.summary || '');
  doc.moveDown();

  doc.font('Helvetica-Bold').fontSize(13).text(`Fundamentals: ${a.fundamentals_trend || ''}`);
  doc.font('Helvetica').fontSize(10.5).text(a.fundamentals_reason || '');
  doc.moveDown();

  doc.font('Helvetica-Bold').fontSize(13).text('Ratio Table');
  doc.font('Courier').fontSize(9.5);
  const years = a.years || [];
  const rows = [
    ['Metric', ...years],
    ['Revenue', ...(a.revenue || []).map(fmt)],
    ['Net Profit', ...(a.net_profit || []).map(fmt)],
    ['ROE %', ...(a.roe || []).map(fmt)],
    ['ROCE %', ...(a.roce || []).map(fmt)],
    ['Debt/Equity', ...(a.debt_to_equity || []).map(fmt)],
    ['Operating Cash Flow', ...(a.operating_cash_flow || []).map(fmt)],
  ];
  rows.forEach((r) => doc.text(r.join('   |   ')));
  doc.moveDown();

  doc.font('Helvetica-Bold').fontSize(13).text('Key Ratios (latest)');
  doc.font('Helvetica').fontSize(10.5).text(
    `Current ratio: ${fmt(a.current_ratio)}    Interest coverage: ${fmt(a.interest_coverage)}    Operating margin: ${fmt(a.operating_margin)}%    Net margin: ${fmt(a.net_margin)}%`
  );
  doc.moveDown();

  doc.font('Helvetica-Bold').fontSize(13).text('Risks Flagged by Management');
  doc.font('Helvetica').fontSize(10.5);
  (a.risks || []).forEach((r) => {
    doc.font('Helvetica-Bold').text(`• ${r.title}`, { continued: false });
    doc.font('Helvetica').text(r.note || '', { indent: 14 });
    doc.moveDown(0.3);
  });
  doc.moveDown();

  if (a.governance_notes || a.promoter_holding_change) {
    doc.font('Helvetica-Bold').fontSize(13).text('Governance Notes');
    doc.font('Helvetica').fontSize(10.5).text(a.governance_notes || '');
    if (a.promoter_holding_change) {
      doc.moveDown(0.3);
      doc.font('Helvetica-Bold').text('Promoter holding: ', { continued: true }).font('Helvetica').text(a.promoter_holding_change);
    }
    doc.moveDown();
  }

  doc.fontSize(8).fillColor('#888').text(
    'This report is descriptive analysis of public filings, not investment advice.',
    { align: 'left' }
  );

  doc.end();
});

module.exports = router;
